services:
  postgres:
    image: postgres:16-alpine
    container_name: movies-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies_dm_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: movies-api
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env.development
  #   volumes:
  #     - ./src:/app/src
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
